package com.templeosrs.util.collections;

import lombok.RequiredArgsConstructor;

/**
 * Categories that can be used in the chat command.
 * Note: the command falls back to the input value, so may capture items not in this list if it has not been updated
 *
 * @link <a href="https://templeosrs.com/api/collection-log/category_parameters.php">Full category list</a>
 */
@RequiredArgsConstructor
public enum CollectionLogCategorySlug {
    // Bosses
    abyssal_sire,
    alchemical_hydra,
    amoxliatl,
    araxxor,
    barrows_chests,
    bryophyta,
    callisto_and_artio,
    cerberus,
    chaos_elemental,
    chaos_fanatic,
    commander_zilyana,
    corporeal_beast,
    crazy_archaeologist,
    dagannoth_kings,
    duke_sucellus,
    the_fight_caves,
    fortis_colosseum,
    the_gauntlet,
    general_graardor,
    giant_mole,
    grotesque_guardians,
    hespori,
    hueycoatl,
    the_inferno,
    kalphite_queen,
    king_black_dragon,
    kraken,
    kreearra,
    kril_tsutsaroth,
    the_leviathan,
    moons_of_peril,
    nex,
    the_nightmare,
    obor,
    phantom_muspah,
    royal_titans,
    sarachnis,
    scorpia,
    scurrius,
    skotizo,
    tempoross,
    thermonuclear_smoke_devil,
    vardorvis,
    venenatis_and_spindel,
    vetion_and_calvarion,
    vorkath,
    the_whisperer,
    wintertodt,
    yama,
    zalcano,
    zulrah,

    // Raids
    chambers_of_xeric,
    theatre_of_blood,
    tombs_of_amascut,

    // Clues
    beginner_treasure_trails,
    easy_treasure_trails,
    medium_treasure_trails,
    hard_treasure_trails,
    elite_treasure_trails,
    master_treasure_trails,
    hard_treasure_trails_rare,
    elite_treasure_trails_rare,
    master_treasure_trails_rare,
    shared_treasure_trail_rewards,

    // Minigames
    barbarian_assault,
    brimhaven_agility_arena,
    castle_wars,
    fishing_trawler,
    giants_foundry,
    gnome_restaurant,
    guardians_of_the_rift,
    hallowed_sepulchre,
    last_man_standing,
    magic_training_arena,
    mahogany_homes,
    mastering_mixology,
    pest_control,
    rogues_den,
    shades_of_mortton,
    soul_wars,
    temple_trekking,
    tithe_farm,
    trouble_brewing,
    volcanic_mine,
    aerial_fishing,

    // Other
    all_pets,
    camdozaal,
    champions_challenge,
    chompy_bird_hunting,
    colossal_wyrm_agility,
    creature_creation,
    cyclopes,
    elder_chaos_druids,
    forestry,
    fossil_island_notes,
    gloughs_experiments,
    hunter_guild,
    monkey_backpacks,
    motherlode_mine,
    my_notes,
    random_events,
    revenants,
    rooftop_agility,
    shayzien_armour,
    shooting_stars,
    skilling_pets,
    slayer,
    tormented_demons,
    tzhaar,
    miscellaneous,

    // Custom
    gilded,
    thirdage,
}